language: python
python:
  - "3.12"
dist: jammy
install:
  - pip install uv
  - uv pip install --system -e ".[dev]"
script:
  - pytest tellsticknet
  - black --version
  - white --check tellsticknet
  - pylint -E tellsticknet
  - flake8 --version
  - flake8 tellsticknet
  - yamllint tellsticknet-sample.conf
